# -*- coding: utf-8 -*-
"""Untitled12.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/13qgGR_rfm6LQqi112pO_Iacm3XLkaXt9
"""

import pyspark